name: Restart Panel Server

on:
  push:
    branches:
      - main

jobs:
  restart_pterodactyl_server:
    runs-on: ubuntu-latest

    steps:
      - name: Restart Server via Panel API
        env:
          PANEL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}
          PANEL_SERVER_ID: ${{ vars.PTERODACTYL_SERVER_ID }}
        run: |
          echo "Restarting server with ID: ${PANEL_SERVER_ID}"
          curl -X POST "https://panel.code-sphere.de/api/client/servers/${PANEL_SERVER_ID}/power" \
            -H "Authorization: Bearer $PANEL_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"signal": "restart"}'
